### ISSUE TITLE
Формирование пути

### ISSUE THREAD

**Issue by Sovgut** [DevRuBu/Web-leveling#1]
https://github.com/DevRuBu/Web-leveling/blob/3f98d7e872c3af519ef5d1b3e8a71bfcb9d6996d/index.js#L15

https://github.com/DevRuBu/Web-leveling/blob/3f98d7e872c3af519ef5d1b3e8a71bfcb9d6996d/index.js#L18

Для правильно работы во всех ОС нужно правильно формировать строки с путями
Ты почти верно это сделал изначально

Вот так итоговая строка собирается:
```path.normalize(path.join(__dirname, 'views', 'layouts'))```

**Comment by DevRuBu** [comment]
https://github.com/DevRuBu/Web-leveling/commit/7a32035f0fad8220b4500cc4ec9bcee9f850dc31
Commits on Apr 16, 2020 [Commmit revrite version 0w.2t]
file: Web-leveling/index.js
line: 15
