### ISSUE TITLE
Отправка формы

### ISSUE THREAD

**Issue by Sovgut** [DevRuBu/Web-leveling#10]
https://github.com/DevRuBu/Web-leveling/blob/03e755120200e7991ff1ba0dbd2f4d54c420ca36/views/page.hbs#L23-L25

Так как у тебя серверный рендеринг, ты можешь выполнять запросы используя форму

`<form action="/34" method="DELETE">...</form>`
`<form action="/4" method="PUT">...</form>`
`<form action="/84" method="POST">...</form>`

(`/34`, `/4`, `/84` это id поста, это примерное число, в этом месте следует использовать реальный id поста)

Либо изменить атрибут `submit` на `button` у элементов `button` внутри формы

**Comment by DevRuBu** [comment]
commit: https://github.com/DevRuBu/Web-leveling/commit/62d42b9cf541f966d179454cb5773cb56146ab90
file:  Web-leveling/views/page.handlebars 
line:20-23
