### ISSUE TITLE
Переменная var и деструктуризация

### ISSUE THREAD

**Issue by Sovgut** [DevRuBu/Web-leveling#4]
https://github.com/DevRuBu/Web-leveling/blob/3f98d7e872c3af519ef5d1b3e8a71bfcb9d6996d/index.js#L89

Никогда не используй ```var``` в своих проектах, это очень проблемное объявление переменной и устаревший синтаксис, в место него используй ```const``` или если у тебя переменная может измениться ```let```

Так же в деструктуризации можно не указывать новое имя свойства и написать короче
```const { title, text } = req.body;```

**Comment by DevRuBu** [comment]
https://github.com/DevRuBu/Web-leveling/commit/7a32035f0fad8220b4500cc4ec9bcee9f850dc31
Commits on Apr 16, 2020 [Commmit revrite version 0w.2t]
file: Web-leveling/index.js
line: 87
