### ISSUE TITLE
Использование jquery

### ISSUE THREAD

**Issue by Sovgut** [DevRuBu/Web-leveling#5]
https://github.com/DevRuBu/Web-leveling/blob/3f98d7e872c3af519ef5d1b3e8a71bfcb9d6996d/scripts.js#L2

По возможности не используй jquery вовсе, он больше не нужен после того как в javascript добавили все недостающие удобные методы

В данном случае используй для выполнения запроса метод ```fetch```, как им пользоваться почитай в MDN документации

**Comment by DevRuBu** [comment]
https://github.com/DevRuBu/Web-leveling/commit/7a32035f0fad8220b4500cc4ec9bcee9f850dc31
Commits on Apr 16, 2020 [Commmit revrite version 0w.2t]
file: Web-leveling\views\layouts\js\app.js
change in all methods
