### ISSUE TITLE
Использование var

### ISSUE THREAD

**Issue by Sovgut** [DevRuBu/Web-leveling#6]
https://github.com/DevRuBu/Web-leveling/blob/3f98d7e872c3af519ef5d1b3e8a71bfcb9d6996d/views/index.hbs#L145

Никогда не используй ```var```, вместо него используй ```const``` или если у тебя переменная может измениться, используй ```let```

**Comment by DevRuBu** [comment]
https://github.com/DevRuBu/Web-leveling/commit/7a32035f0fad8220b4500cc4ec9bcee9f850dc31
Commits on Apr 16, 2020 [Commmit revrite version 0w.2t]
file: Web-leveling\views\layouts\js\app.js
change in all methods
