### ISSUE TITLE
Маршрутизация

### ISSUE THREAD

**Issue by Sovgut** [DevRuBu/Web-leveling#7]
https://github.com/DevRuBu/Web-leveling/blob/03e755120200e7991ff1ba0dbd2f4d54c420ca36/index.js#L17

Так как ты используешь серверный рендеринг, тебе не нужно выполнять на клиентской стороне запросы для выполнения CRUD действий, потому `/api/blog` стоит изменить на `/` так как такой маршрут не приносит никакой пользы, лишь усложняет навигацию по приложению.

**Comment by DevRuBu** [comment]
https://github.com/DevRuBu/Web-leveling/commit/7a32035f0fad8220b4500cc4ec9bcee9f850dc31
Commits on Apr 16, 2020 [Commmit revrite version 0w.2t]
file: Web-leveling/index.js
line: 18
