### ISSUE TITLE
Вывод в консоль

### ISSUE THREAD

**Issue by Sovgut** [DevRuBu/Web-leveling#8]
https://github.com/DevRuBu/Web-leveling/blob/03e755120200e7991ff1ba0dbd2f4d54c420ca36/index.js#L83

Для чего эта строка?

**Comment by DevRuBu** [comment]
это я уже убрал, пробовал в консоль вывести ссылку

**Comment by Sovgut** [comment]
выведи просто `Server is start on ${port}. http://localhost:${port}`

**Comment by DevRuBu** [comment]
ок

**Comment by DevRuBu** [comment]
https://github.com/DevRuBu/Web-leveling/commit/7a32035f0fad8220b4500cc4ec9bcee9f850dc31
Commits on Apr 16, 2020 [Commmit revrite version 0w.2t]
file: Web-leveling/index.js
line: 94
