### ISSUE TITLE
Абсолютные пути в ссылках

### ISSUE THREAD

**Issue by Sovgut** [DevRuBu/Web-leveling#9]
https://github.com/DevRuBu/Web-leveling/blob/03e755120200e7991ff1ba0dbd2f4d54c420ca36/views/index.hbs#L15-L18

Вместо абсолютных путей нужно использовать относительные пути.
К примеру:
`/blog/1`

**Comment by DevRuBu** [comment]
https://github.com/DevRuBu/Web-leveling/commit/7a32035f0fad8220b4500cc4ec9bcee9f850dc31
Commits on Apr 16, 2020 [Commmit revrite version 0w.2t]
file: Web-leveling/views/page.handlebars
line: 31

file: Web-leveling/views/index.handlebars
line: 18
